### ISSUE TITLE
Help with the student package

### ISSUE THREAD

**Issue by dcapeletti** [bakatz/Chess#1]
I would like to contribute to this project but I can not compile it in Eclipse because the student package is not found. Do you know how I can get it? 

![student](https://user-images.githubusercontent.com/5890886/28947378-f27fde40-7885-11e7-8553-f9ae56d8f7cf.png)

Thanks

**Comment by bakatz** [comment]
This was one of my student projects from many years ago - as far as I recall, our instructor gave us an eclipse extension that allowed us to run special GUI tests, but I have no idea where that code lives now.

Best of luck

**Comment by bakatz** [comment]
Should also mention that I have a full time job and don't have much time to review PRs for this project - feel free to fork the project and make some changes though
